#!/bin/bash

burn() {
  cdrecord -v -tao dev=/dev/dvd driveropts=burnfree -pad -audio *.wav

  echo "Finished burning, would you like to delete the waves files? yes/no"
  read answer

  until [ yes = "$answer" ]; do
    burn
  done

  rm *.wav
}

for mp3 in *.[MmOoMm][PpGg4][3GgAa]; do
  mv "$mp3" "${mp3// /_}"

  lame --decode "$mp3" ${mp3/.mp3}.wav
  normalize *.wav
  burn
done
